import type { PropsWithChildren } from "react";
import type { Metadata } from 'next';

import Nav from "@/components/nav";
import Footer from "../components/footer/footer";

import { Providers } from "@/providers";
import './globals.css';

export const metadata: Metadata = {
  title: 'Humanitarian Aid',
  description: 'Generated by create next app',
};

/**
 * Layout principal de la aplicación.
 * 
 * @param param0 - Props por defecto de un componente.
 * 
 * @returns { JSX.Element } Layout principal de la aplicación.
 */
export default function RootLayout({
  children,
}: PropsWithChildren): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Nav />
          { children }
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
