import type { PropsWithChildren } from "react";
import type { Metadata } from 'next';

import Nav from "@/components/nav";
import Footer from "../components/footer/footer";

import { Providers } from "@/providers";
import './globals.css';

export const metadata: Metadata = {
  title: 'Humanitarian Aid',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Nav />
          { children }
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
