import type { PropsWithChildren } from "react";
import type { Metadata } from 'next';

import { Providers } from "@/providers";
import './globals.css';

export const metadata: Metadata = {
  title: 'Ayuda Humanitaria',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
